### ISSUE TITLE
Support bibliography

### ISSUE THREAD

**Issue by fritz-hh** [gaurav-nelson/asciidoc-reference-check#2]
Thank you for providing this extension!

It would be very cool, if the extension would support bibliography with inbound reference, that it currently fails to verify!
This type of anchor is using the following format: [[[pp]]], and is located in an unordered list.
(see https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#bibliography)

**Comment by gaurav-nelson** [comment]
Does #3 fixes this?

**Comment by fritz-hh** [comment]
Yes #3 fixes this!
