### ISSUE TITLE
Support references to sections of other documents

### ISSUE THREAD

**Issue by fritz-hh** [gaurav-nelson/asciidoc-reference-check#6]
Thank you for developing this helpful tool!

Currently, asciidoc-reference-check supports references to other documents but does not support references to specific sections of other asciidoc documents.

e.g.: `<<path/to/file.adoc#section-a, some description>>`

That would be a quite major change, as  asciidoc-reference-check would have to analyze the referenced document content too, but it would be very helpful

**Comment by gaurav-nelson** [comment]
Thank you for the issue and PR, I have not updated this in a long time. Please bare with me while I set it up and test these changes.

**Comment by fritz-hh** [comment]
Your welcome.
Take your time. There's no rush 😊

**Comment by gaurav-nelson** [comment]
Thanks for all your work on improving this. 
Right now it checks for anchors in current file, and also checks for specified anchors in external files. For example, for the external ref `<<path/to/file.adoc#section-a, some description>>`:

1. It first checks if the file `file.adoc` exists, (error outs if it doesn't)
2. If file exist, it checks if the anchor `section-1` exist in that file.

Let me know if I am wrong in understanding what you mean here.

**Comment by fritz-hh** [comment]
Sorry. I did not realize that this check was already there. Now I see it :-)
I will close this issue.
