### ISSUE TITLE
Support recursive check from the tree viewer

### ISSUE THREAD

**Issue by fritz-hh** [gaurav-nelson/asciidoc-reference-check#9]
It would be very helpful to be able to launch the reference check from the TreeView.
The feature should perform a recurve check if the function is launched from a folder

**Comment by fritz-hh** [comment]
I could send you a pull request for this new feature, but I would prefer to prepare the pull request after I have merged the previous ones. That way It would be easier for merge the changed related to this ticket.

**Comment by gaurav-nelson** [comment]
Thanks for using this and identifying various issues and suggesting better functionality. I am just caught up in some things, and will try to go through the existing PRs over the weekend. Thanks again @fritz-hh

**Comment by gaurav-nelson** [comment]
I have managed to merge all PRs and update the extension, please do create a pull request if you have more to add. 👍 🥇

**Comment by fritz-hh** [comment]
Cool. I will try to do that as soon as possible.

**Comment by fritz-hh** [comment]
This is solved by #10

**Comment by fritz-hh** [comment]
Solved by #18
